schema_version: 1

context:
  name: lbaplocal
  version: 0.7.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/LbAPLocal-${{ version }}.tar.gz
  sha256: 76f6d83e6ddea5f3e54b17aadef3e0066cadc39bf5a4de880202f22d1675b0b0

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - lb-ap = LbAPLocal.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}
    - lbapcommon >=0.10.2
    - lbdiracwrappers
    - lbenv
    - lbprodrun >=1.3,<2.dev0
    - apd >=0.6.0
    - click
    - consolemd
    - mplhep
    - requests
    - setuptools

tests:
  - python:
      imports:
        - LbAPLocal
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - lb-ap --help

about:
  summary: Tool to locally run tests for AnalysisProductions
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  repository: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal

extra:
  recipe-maintainers:
    - AidanWiederhold
    - chrisburr
