schema_version: 1

context:
  name: lbaplocal
  version: "0.10.2"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/96/76/a68155532b5153f6b278e28c4d775089fa0a7ef9c139ed34331c09c725d1/lbaplocal-${{ version }}.tar.gz
  sha256: 3ddb01f232df57485473242bc2f8545899a7180f1887207535e1c3887843087a

build:
  number: 0 # added prmon
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - lb-ap = LbAPLocal.cli.main:app
      - lb-ap-legacy = LbAPLocal.cli.legacy:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}
    - lbapcommon >=0.15.11
    - dirac-cwl >=1.1.3
    - textual
    - textual-plotext
    - lbdiracwrappers
    - lbenv
    - lbprodrun >=1.12.2,<2.dev0
    - apd >=0.6.0
    - click
    - consolemd
    - mplhep
    - requests
    - setuptools
    - nodejs
    - quickjs
    - prmon
    - questionary

tests:
  - python:
      python_version: ["${{ python_min }}.*", "*"]
      imports:
        - LbAPLocal
      pip_check: true

about:
  summary: Tool to locally run tests for AnalysisProductions
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal
  repository: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/lbaplocal

extra:
  recipe-maintainers:
    - ryuwd
    - AidanWiederhold
    - chrisburr
